title: "Configure ApplicationPool for Pydio in Windows2012 & IIS8 [Update Pydio 6]"
language: und
category: Pydio 8
abstract: "[Deprecated] This article shows How-to, to configure Pydio to run inside an Application Pool."
tags: application pool
  iis8
  iis_iusrs
  process worker
  virtual directory
  windows 2012
  windows server
  windows server 2012
